#!/usr/bin/env node

import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';

const projectRoot = path.resolve(import.meta.dirname, '..');
const entryId = 'js/main.js';
const outputPath = path.join(projectRoot, 'js/lawscape.bundle.js');
const checkOnly = process.argv.includes('--check');
const modules = new Map();

function normalizeId(filePath) {
  return filePath.split(path.sep).join('/');
}

function resolveId(fromId, request) {
  return normalizeId(path.normalize(path.join(path.dirname(fromId), request)));
}

function exportedNames(source) {
  return [...source.matchAll(/\bexport\s+(?:const|let|class|function)\s+([A-Za-z_$][\w$]*)/g)]
    .map((match) => match[1]);
}

async function collectModule(id) {
  if (modules.has(id)) return;

  const absolutePath = path.join(projectRoot, id);
  let source = await readFile(absolutePath, 'utf8');
  const dependencies = [];

  source = source.replace(
    /import\s*\{([\s\S]*?)\}\s*from\s*['"]([^'"]+)['"];?/g,
    (_statement, bindings, request) => {
      const dependencyId = resolveId(id, request);
      dependencies.push(dependencyId);
      const cleanBindings = bindings.replace(/\s+/g, ' ').trim();
      return `const { ${cleanBindings} } = require(${JSON.stringify(dependencyId)});`;
    },
  );

  const names = exportedNames(source);
  source = source.replace(
    /\bexport\s+(const|let|class|function)\s+([A-Za-z_$][\w$]*)/g,
    '$1 $2',
  );

  modules.set(id, { source, names });
  for (const dependencyId of dependencies) await collectModule(dependencyId);
}

function indent(source, spaces) {
  const prefix = ' '.repeat(spaces);
  return source.split('\n')
    .map((line) => line ? `${prefix}${line.replace(/[ \t]+$/g, '')}` : '')
    .join('\n');
}

function renderBundle() {
  const renderedModules = [...modules.entries()].map(([id, module]) => {
    const assignments = module.names.length
      ? `\nObject.assign(exports, { ${module.names.join(', ')} });`
      : '';
    return `${JSON.stringify(id)}: (exports, require) => {\n`
      + `${indent(module.source.trimEnd(), 4)}`
      + `${indent(assignments, 4)}\n  }`;
  }).join(',\n  ');

  return `/* LawScape browser bundle.
 * Generated by scripts/build.mjs from the source modules in js/.
 * Do not edit this file directly.
 */
(function () {
  'use strict';

  const modules = {
  ${renderedModules}
  };
  const cache = Object.create(null);

  function require(id) {
    if (cache[id]) return cache[id];
    const factory = modules[id];
    if (!factory) throw new Error(\`LawScape module not found: \${id}\`);
    const exports = {};
    cache[id] = exports;
    factory(exports, require);
    return exports;
  }

  require(${JSON.stringify(entryId)});
}());
`;
}

await collectModule(entryId);
const bundle = renderBundle();

if (checkOnly) {
  let existing = '';
  try {
    existing = await readFile(outputPath, 'utf8');
  } catch {
    console.error('Browser bundle is missing. Run npm run build.');
    process.exit(1);
  }
  if (existing !== bundle) {
    console.error('Browser bundle is out of date. Run npm run build.');
    process.exit(1);
  }
  console.log('Browser bundle is current.');
} else {
  await writeFile(outputPath, bundle);
  console.log(`Built ${path.relative(projectRoot, outputPath)} (${modules.size} modules).`);
}
